=== angustyler/xmltv/channels.dtd
<!-- DTD for channel name translations 

Author: Gottfried Szing, suggestions by Ed Avis

Suggestions and problems please mail to goofy@yasd.dhs.org or
epa98@doc.ic.ac.uk.

<?xml version="1.0" encoding="ISO-8859-1"?>
<channels>
  <channel id="3sat.de">
    <display-name lang="de">3SAT</display-name>
  </channel>
  <channel id="das-erste.de">
    <display-name lang="de">ARD</display-name>
    <display-name lang="de">Das Erste</display-name>
  </channel>
</channels>

Each channel has one id attribute, which must be unique and should
preferably be in the form suggested by RFC2838.  Then one or more
display names which are shown to the user.  You might want a different
display name for different languages, but also you can have more than
one name for the same language.  Names listed earlier are considered
'more canonical'.

Since the display name is just there as a way for humans to refer to
the channel, it's acceptable to just put the channel number if it's
fairly universal among viewers of the channel.  But remember that this
isn't an official statement of what channel number has been
allocated, and the same number might be used for a different channel
somewhere else.
-->

<!-- The root tag. -->
<!ELEMENT channels (channel+)>

<!-- One channel.  The id must be unique within a single channels
file. 
-->
<!ELEMENT channel (display-name+) >
<!ATTLIST channel id CDATA #REQUIRED >

<!-- A user-friendly name for the channel - maybe even a channel
number.  List the most canonical / common ones first and the most
obscure names last.  The lang attribute corresponds to abbreviations
mentioned in ISO 3316.
-->
<!ELEMENT display-name (#PCDATA)>
<!ATTLIST display-name lang CDATA #IMPLIED>

=== angustyler/xmltv/channels_nl.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE channels SYSTEM "channels.dtd">

<channels>
    <channel id="3sat.de">
         <display-name lang="de">3SAT</display-name>
         <display-name lang="en">3SAT</display-name>
    </channel>
    <channel id="das-erste.de">
         <display-name lang="de">ARD</display-name>
         <display-name lang="en">ARD</display-name>
    </channel>
    <channel id="arte.de">
         <display-name lang="de">ARTE</display-name>
         <display-name lang="en">ARTE</display-name>
    </channel>
    <channel id="sfb.de">
         <display-name lang="de">B1/SFB</display-name>
         <display-name lang="en">B1/SFB</display-name>
    </channel>
    <channel id="br-online.de">
         <display-name lang="de">BAYERN</display-name>
         <display-name lang="en">BAYERN</display-name>
    </channel>
    <channel id="cartoonnetwork.com">
         <display-name lang="de">CARTOON</display-name>
         <display-name lang="en">CARTOON</display-name>
    </channel>
    <channel id="cnn.com">
         <display-name lang="de">CNN</display-name>
         <display-name lang="en">CNN</display-name>
    </channel>
    <channel id="dsf.de">
         <display-name lang="de">DSF</display-name>
         <display-name lang="en">DSF</display-name>
    </channel>
    <channel id="euronews.net">
         <display-name lang="de">E-NEWS</display-name>
         <display-name lang="en">E-NEWS</display-name>
    </channel>
    <channel id="eurosport.ch">
         <display-name lang="de">E-SPORT</display-name>
         <display-name lang="en">E-SPORT</display-name>
    </channel>
    <channel id="hr-online.de">
         <display-name lang="de">HESSEN</display-name>
         <display-name lang="en">HESSEN</display-name>
    </channel>
    <channel id="kabel1.de">
         <display-name lang="de">KABEL 1</display-name>
         <display-name lang="en">KABEL 1</display-name>
    </channel>
    <channel id="kinderkanal.de">
         <display-name lang="de">KINDER KANAL</display-name>
         <display-name lang="en">KINDER KANAL</display-name>
    </channel>
    <channel id="mdr.de">
         <display-name lang="de">MDR</display-name>
         <display-name lang="en">MDR</display-name>
    </channel>
    <channel id="mtv-home.de">
         <display-name lang="de">MTV</display-name>
         <display-name lang="en">MTV</display-name>
    </channel>
    <channel id="n-tv.de">
         <display-name lang="de">N-TV</display-name>
         <display-name lang="en">N-TV</display-name>
    </channel>
    <channel id="nbc.com">
         <display-name lang="de">NBC</display-name>
         <display-name lang="en">NBC</display-name>
    </channel>
    <channel id="ndrtv.de">
         <display-name lang="de">NORD</display-name>
         <display-name lang="en">NORD</display-name>
    </channel>
    <channel id="orb.de">
         <display-name lang="de">ORB</display-name>
         <display-name lang="en">ORB</display-name>
    </channel>
    <channel id="orf1.orf.at">
         <display-name lang="de">ORF1</display-name>
         <display-name lang="en">ORF1</display-name>
    </channel>
    <channel id="orf2.orf.at">
         <display-name lang="de">ORF2</display-name>
         <display-name lang="en">ORF2</display-name>
    </channel>
    <channel id="phoenix.de">
         <display-name lang="de">PHOENIX</display-name>
         <display-name lang="en">PHOENIX</display-name>
    </channel>
    <channel id="premiere.de">
         <display-name lang="de">PREMIERE</display-name>
         <display-name lang="en">PREMIERE</display-name>
    </channel>
    <channel id="pro7.de">
         <display-name lang="de">PRO 7</display-name>
         <display-name lang="en">PRO 7</display-name>
    </channel>
    <channel id="rtl.de">
         <display-name lang="de">RTL</display-name>
         <display-name lang="en">RTL</display-name>
    </channel>
    <channel id="rtl2.de">
         <display-name lang="de">RTL 2</display-name>
         <display-name lang="en">RTL 2</display-name>
    </channel>
    <channel id="superrtl.de">
         <display-name lang="de">S-RTL</display-name>
         <display-name lang="en">S-RTL</display-name>
    </channel>
    <channel id="sat1.de">
         <display-name lang="de">SAT.1</display-name>
         <display-name lang="en">SAT.1</display-name>
    </channel>
    <channel id="swr-online.de">
         <display-name lang="de">SW III</display-name>
         <display-name lang="en">SW III</display-name>
    </channel>
    <channel id="tm3.de">
         <display-name lang="de">TM3</display-name>
         <display-name lang="en">TM3</display-name>
    </channel>
    <channel id="tnttv.co.uk">
         <display-name lang="de">TNT</display-name>
         <display-name lang="en">TNT</display-name>
    </channel>
    <channel id="trt.net">
         <display-name lang="de">TRT</display-name>
         <display-name lang="en">TRT</display-name>
    </channel>
    <channel id="tv5.org">
         <display-name lang="de">TV5</display-name>
         <display-name lang="en">TV5</display-name>
    </channel>
    <channel id="vh1.de">
         <display-name lang="de">VH1</display-name>
         <display-name lang="en">VH1</display-name>
    </channel>
    <channel id="viva1.viva-tv.de">
         <display-name lang="de">VIVA</display-name>
         <display-name lang="en">VIVA</display-name>
    </channel>
    <channel id="viva2.viva-tv.de">
         <display-name lang="de">VIVA II</display-name>
         <display-name lang="en">VIVA II</display-name>
    </channel>
    <channel id="vox.de">
         <display-name lang="de">VOX</display-name>
         <display-name lang="en">VOX</display-name>
    </channel>
    <channel id="wdr.de">
         <display-name lang="de">WEST</display-name>
         <display-name lang="en">WEST</display-name>
    </channel>
    <channel id="zdf.de">
         <display-name lang="de">ZDF</display-name>
         <display-name lang="en">ZDF</display-name>
    </channel>
</channels>
